plugins {
    id 'java'
    id 'org.springframework.boot' version '3.4.3' // ĐÃ HẠ XUỐNG BẢN 3.4.3 ĐỂ CHẠY MƯỢT MÀ VỚI JAVA 21
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'clc65.quanggck'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21) // Giữ nguyên Java 21 ổn định nhất hiện tại
    }
}

repositories {
    mavenCentral()
}

dependencies {
    // Các thư viện Starter Core của hệ thống
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    
    // Bảo mật Hệ thống nâng cao & Phân quyền Thymeleaf với Spring Security 6
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.thymeleaf.extras:thymeleaf-extras-springsecurity6'
    
    // Driver kết nối hệ quản trị cơ sở dữ liệu MySQL
    runtimeOnly 'com.mysql:mysql-connector-j'
    
    // Công cụ tự động Tải lại ứng dụng khi thay đổi code (Hot-swap)
    developmentOnly 'org.springframework.boot:spring-boot-devtools'
    
    // Các thư viện phục vụ cho Unit Test hệ thống
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.security:spring-security-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
    useJUnitPlatform()
}